services:
  service-a:
    build: ./service-a
    ports:
      - "8080:8080"
    environment:
      - SERVICE_B_URL=http://service-b:8081
    depends_on:
      - service-b
      - zipkin
    networks:
      - app-network

  service-b:
    build: ./service-b
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    depends_on:
      - zipkin
    networks:
      - app-network

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - app-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - zipkin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
